apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pub
  name: pub
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pub
  template:
    metadata:
      labels:
        app: pub
    spec:
      containers:
      - image: loumelini/pub
        imagePullPolicy: Always
        name: pub
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pub
  name: pub
  namespace: project
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: pub
