apiVersion: split.smi-spec.io/v1alpha2
kind: TrafficSplit
metadata:
  name: function-split
  namespace: project
spec:
  # The root service that clients use to connect to the destination application.
  service: load
  # Services inside the namespace with their own selectors, endpoints and configuration.
  backends:
  - service: pub
    weight: 50
  - service: client
    weight: 50